### ISSUE TITLE
Cannot compile under kinetic

### ISSUE THREAD

**Issue by fitter22** [pal-robotics/pal_hardware_gazebo#1]
Hi, I've run into problems with making tiago simulation running. Looks like changes under latest tag - 0.1.1 introduced some bugs. I found out two culprits:
1. https://github.com/pal-robotics/pal_hardware_gazebo/commit/65fc2b9df05734dfd34670ab7eeb67f6865b47b2
`imu_sensor->SetWorldToReferencePose();` is not avaible in Gazebo 7.0.0 (which is shipped with ROS Kinetic afaik). Btw I found that method in Gazebo 7.12.0
2. Probably `tiago_public.rosinstall` from tiago simulation tutorial needs a little update, exactly this line: 
`- git: {local-name: dynamic_introspection,        uri: 'https://github.com/pal-robotics/dynamic_introspection', version: 'master'}` -> I think the correct branch should be `kinetic-devel`. Branch master has a different header filename and it makes a problem with this commit: https://github.com/pal-robotics/pal_hardware_gazebo/commit/b1fe0f1aa19054f6e49cbbcf35c3c1420fa3bb3c

Dirty workaround for now its to checkout to older 0.1.0 tag

**Comment by v-lopez** [comment]
Hi @fitter22 I've pushed a fix for the rosinstall file, and one of my colleagues is working on the pal_hardware_gazebo fix.

Thanks for reporting it.

**Comment by v-lopez** [comment]
Should be fixed by: https://github.com/pal-robotics/pal_hardware_gazebo/commit/a7896d37c784881af051afa60f31b9149a6248d2

**Comment by fitter22** [comment]
Hi @v-lopez I've checked it now, unfortunately the problem still occurs.
`/home/fitter/tiago_public_ws/src/pal_hardware_gazebo/src/pal_hardware_gazebo.cpp:290:17: error: ‘class gazebo::sensors::ImuSensor’ has no member named ‘SetWorldToReferenceOrientation’
     imu_sensor->SetWorldToReferenceOrientation(ignition::math::Quaterniond::Identity);`

Looks like a new function `SetWorldToReferenceOrientation` is also missing in gazebo 7.0.0 API.
You can find it here [https://bitbucket.org/osrf/gazebo/src/a29d8dabed9a14fb6bafdcd31c84b160c00b127c/gazebo/sensors/ImuSensor.hh?at=gazebo7_7.0.0&fileviewer=file-view-default](url)

I'm using gazebo from gazebo7 pkg from ubuntu xenial repository which has it on 7.0.0+dfsg-2 version.
Should I use another version of gazebo then?

Thank you

**Comment by fitter22** [comment]
Just a small update on this issue. 
Yesterday I set up TIAGo simulation on PC with clean Kinetic installation. I managed to build everything without any errors, so looks like the problems mentioned above are fixed.
Thank you for your help @v-lopez!
